version: "3.9"

services:
  db:
    image: postgres:16
    container_name: barbearia-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "#abc123#"
      POSTGRES_DB: barbearia
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d barbearia"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  adminer:
    image: adminer:4
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db

  api:
    build: ./api
    container_name: barbearia-api
    environment:
      DATABASE_URL: postgres://postgres:%23abc123%23@db:5432/barbearia
      PORT: 4000
      ALLOWED_ORIGIN: http://localhost:5173,http://127.0.0.1:5173,http://localhost:5174
      ADMIN_TOKEN: admin123
      SHIFT_START_HOUR: 5
      TZ: America/Sao_Paulo
    # Espera o Postgres ficar OK, depois inicia
    command: sh -c "apk add --no-cache postgresql16-client >/dev/null 2>&1 || apk add --no-cache postgresql15-client; until pg_isready -h db -p 5432 -U postgres -d barbearia; do echo 'Aguardando DB...'; sleep 2; done; npm start"
    ports:
      - "4000:4000"
    depends_on:
      - db
    restart: unless-stopped

  web:
    build: ./web
    container_name: barbearia-web
    environment:
      VITE_API_BASE: http://localhost:4000
      VITE_DEFAULT_SHOP: dersobarbearia
    command: ["npm","run","dev","--","--host"]
    ports:
      - "5173:5173"
    depends_on:
      - api
    restart: unless-stopped

volumes:
  db_data:
